# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18pGDNmed6AAqaWXJugmUjZtPmK-ZjD6Y
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

try:
    dados = pd.read_csv("compras.csv")
except:
    dados = pd.DataFrame({"produto": [], "preco": []})
    dados.to_csv("compras.csv", index=False)

st.title("controle de gastos")
orcamento = st.number_input("orçamento:", min_value=0.0)

total = dados["preco"].sum() if not dados.empty else 0
with st.form("nova_compra"):
    produto = st.text_input("produto:")
    preco = st.number_input("preço:", min_value=0.0)

    if st.form_submit_button("adicionar"):
        if preco <= (orcamento - total):
            nova_linha = pd.DataFrame({"produto": [produto], "preco": [preco]})
            dados = pd.concat([dados, nova_linha])
            dados.to_csv("compras.csv", index=False)
            st.success("compra adicionada!")
        else:
            st.error("sem orçamento suficiente!")

    if orcamento > 0:
        fig, ax = plt.subplots(figsize=(8, 8))
        if not dados.empty:
            produtos = dados["produto"].tolist()
            valores = dados["preco"].tolist()
            restante = orcamento - total
        if restante > 0:
            produtos.append("disponível")
            valores.append(restante)
        plt.pie(
            valores,
            labels=produtos,
            autopct='%1.1f%%',
            pctdistance=0.85
        )
        plt.title(f"orçamento: {orcamento}€")
        centro = plt.Circle((0, 0), 0.70, fc='white')
        ax.add_artist(centro)
    st.pyplot(fig)
    st.dataframe(dados)
    st.write(f"total gasto: {total}€")
    st.write(f"resta: {orcamento - total}€")
